# Generated by Django 6.0.3 on 2026-08-30 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_favoritetrack_user_playlist_user_track_audio_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='bpm',
            field=models.PositiveIntegerField(db_index=True, default=120),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre',
            field=models.CharField(db_index=True, default='Alternative', max_length=60),
        ),
        migrations.AlterField(
            model_name='track',
            name='plays_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
    ]
